pull_request_rules:
  - name: backport patches to v1.x branch
    conditions:
      - base=main
      - label=backport:v1.x
    actions:
      backport:
        branches:
          - v1.x
  - name: backport patches to v2.x branch
    conditions:
      - base=main
      - label=backport:v2.x
    actions:
      backport:
        branches:
          - v2.x
  - name: forward-port patches to main branch
    conditions:
      - base=v1.x
      - label=forwardport:main
    actions:
      backport:
        branches:
          - main
  - name: forward-port patches to main branch
    conditions:
      - base=v2.x
      - label=forwardport:main
    actions:
      backport:
        branches:
          - main
