version: '3'

services:
  core0:
    container_name: core0
    build:
      context: ../..
      args:
        CELESTIA_HOME_DIR: /opt
    environment:
      - MY_VAL_ADDRESS=celes1d9qrpq56t765g9umqwhvey3vn25fcmf8f6yeyx
      - DALC_ADDRESS=celes1dm7fp7uwrr5y68v48gg8jhd2cku7vt7f4l8w0s
    ports:
      - "9090:9090"
      - "26657:26657"
    command: [
        "/bin/celestia-appd",
        "start", "--home", "/opt",
        "--moniker", "core0",
        "--rpc.laddr", "tcp://0.0.0.0:26657"
    ]
    volumes:
      - ${PWD}/celestia-app/core0/config/priv_validator_key.json:/opt/config/priv_validator_key.json:ro
      - ${PWD}/celestia-app/core0/config/node_key.json:/opt/config/node_key.json:ro
      - ${PWD}/celestia-app/core0/keyring-test:/opt/keyring-test:ro
      - ${PWD}/celestia-app/config.toml:/opt/config/config.toml:ro
      - ${PWD}/celestia-app/genesis.json:/opt/config/genesis.json:ro

  core1:
    container_name: core1
    build:
      context: ../..
      args:
        CELESTIA_HOME_DIR: /opt
    environment:
      - MY_VAL_ADDRESS=celes1e5yt4l20alra9gtl4d9uncc4lm23zdxsjqhmsz
    command: [
        "/bin/bash",
        "/opt/start_node_and_create_validator_core1.sh"
    ] # celestia-appd start --home /opt --moniker core1 --p2p.persistent_peers 7b5ef9ef378a3907be7591863a566634d191b58b@core0:26656 --rpc.laddr tcp://0.0.0.0:26657
    volumes:
      - ${PWD}/celestia-app/core1/config/priv_validator_key.json:/opt/config/priv_validator_key.json:ro
      - ${PWD}/celestia-app/core1/config/node_key.json:/opt/config/node_key.json:ro
      - ${PWD}/celestia-app/core1/keyring-test:/opt/keyring-test:ro
      - ${PWD}/celestia-app/core1/create_core1_validator.sh:/opt/create_core1_validator.sh:ro
      - ${PWD}/celestia-app/core1/start_node_and_create_validator_core1.sh:/opt/start_node_and_create_validator_core1.sh:ro
      - ${PWD}/celestia-app/config.toml:/opt/config/config.toml:ro
      - ${PWD}/celestia-app/genesis.json:/opt/config/genesis.json:ro

  core2:
    container_name: core2
    build:
      context: ../..
      args:
        CELESTIA_HOME_DIR: /opt
    environment:
      - MY_VAL_ADDRESS=celes1qqan0fj73dhqfgwkuuh4qj2e77g4tugkrhy2jn
    command: [
      "/bin/bash",
      "/opt/start_node_and_create_validator_core2.sh"
    ]
    volumes:
      - ${PWD}/celestia-app/core2/config/priv_validator_key.json:/opt/config/priv_validator_key.json:ro
      - ${PWD}/celestia-app/core2/config/node_key.json:/opt/config/node_key.json:ro
      - ${PWD}/celestia-app/core2/keyring-test:/opt/keyring-test:ro
      - ${PWD}/celestia-app/core2/create_core2_validator.sh:/opt/create_core2_validator.sh:ro
      - ${PWD}/celestia-app/core2/start_node_and_create_validator_core2.sh:/opt/start_node_and_create_validator_core2.sh:ro
      - ${PWD}/celestia-app/config.toml:/opt/config/config.toml:ro
      - ${PWD}/celestia-app/genesis.json:/opt/config/genesis.json:ro

  core3:
    container_name: core3
    build:
      context: ../..
      args:
        CELESTIA_HOME_DIR: /opt
    environment:
      - MY_VAL_ADDRESS=celes1gf9hty6c0pwp7h763lz5gf4hng55prscdv8q79
    command: [
      "/bin/bash",
      "/opt/start_node_and_create_validator_core3.sh"
    ]
    volumes:
      - ${PWD}/celestia-app/core3/config/priv_validator_key.json:/opt/config/priv_validator_key.json:ro
      - ${PWD}/celestia-app/core3/config/node_key.json:/opt/config/node_key.json:ro
      - ${PWD}/celestia-app/core3/keyring-test:/opt/keyring-test:ro
      - ${PWD}/celestia-app/core3/create_core3_validator.sh:/opt/create_core3_validator.sh:ro
      - ${PWD}/celestia-app/core3/start_node_and_create_validator_core3.sh:/opt/start_node_and_create_validator_core3.sh:ro
      - ${PWD}/celestia-app/config.toml:/opt/config/config.toml:ro
      - ${PWD}/celestia-app/genesis.json:/opt/config/genesis.json:ro

  ganache:
#    image: ethereum/client-go:alltools-stable
#    command: [
#        "geth",
#        "--datadir=/root/.ethereum/devchain",
##        "--nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322",
#        "--http.api=personal,db,eth,net,web3,txpool,miner",
#        "--http.corsdomain=*",
#        "--maxpeers=0",
#        "--networkid=1234", "--http", "--http.addr=0.0.0.0", "--mine"
#    ]
#    volumes:
##      - ${PWD}/ethereum/password:/root/files/password:ro
#      - ${PWD}/ethereum/genesis.json:/root/files/genesis.json:ro
#      - ${PWD}/ethereum/keystore:/root/.ethereum/devchain/keystore:ro
    image: trufflesuite/ganache-cli
    command: [
      "--port=8545",
      "--host=0.0.0.0",
      "--networkId=1234",
      "--chainId=1234",
      "--account=\"0x1ebff46d79a475ef795be8e8edeb8f7906270af8ad26ba9231b552c3f48c91f9,0x90000000000000000000000\""
    ]
    ports:
      - "8545:8545"
