version: '3'

services:
  core0:
    container_name: core0
    build:
      context: ../..
      args:
        CELESTIA_HOME_DIR: /opt
    ports:
      - "9090:9090"
      - "26657:26657"
    command: [
        "/bin/celestia-appd",
        "start", "--home", "/opt",
        "--moniker", "core0",
        "--rpc.laddr", "tcp://0.0.0.0:26657"
    ]
    # Eth Address: 0x966e6f22781EF6a6A82BBB4DB3df8E225DfD9488:da6ed55cb2894ac2c9c10209c09de8e8b9d109b910338d5bf3d747a7e1fc9eb9
    volumes:
      - ${PWD}/celestia-app/core0/config/priv_validator_key.json:/opt/config/priv_validator_key.json:ro
      - ${PWD}/celestia-app/core0/config/node_key.json:/opt/config/node_key.json:ro
      - ${PWD}/celestia-app/core0/keyring-test:/opt/keyring-test:ro
      - ${PWD}/celestia-app/config.toml:/opt/config/config.toml:ro
      - ${PWD}/celestia-app/genesis.json:/opt/config/genesis.json:ro

  core1:
    container_name: core1
    build:
      context: ../..
      args:
        CELESTIA_HOME_DIR: /opt
    depends_on:
      - core0
    environment:
      - MONIKER=core1
      - CELESTIA_HOME=/opt
      # private key: 002ad18ca3def673345897b063bfa98d829a4d812dbd07f1938676828a82c4f9
      - ETH_ADDRESS=0x91DEd26b5f38B065FC0204c7929Da1b2A21877Ad
      - AMOUNT=5000000000uceles
    command: [
        "/bin/bash",
        "/opt/start_node_and_create_validator.sh"
    ] # celestia-appd start --home /opt --moniker core1 --p2p.persistent_peers 7b5ef9ef378a3907be7591863a566634d191b58b@core0:26656 --rpc.laddr tcp://0.0.0.0:26657
    volumes:
      - ${PWD}/celestia-app/core1/config/priv_validator_key.json:/opt/config/priv_validator_key.json:ro
      - ${PWD}/celestia-app/core1/config/node_key.json:/opt/config/node_key.json:ro
      - ${PWD}/celestia-app/core1/keyring-test:/opt/keyring-test:ro
      - ${PWD}/celestia-app/start_node_and_create_validator.sh:/opt/start_node_and_create_validator.sh:ro
      - ${PWD}/celestia-app/config.toml:/opt/config/config.toml:ro
      - ${PWD}/celestia-app/genesis.json:/opt/config/genesis.json:ro

  core2:
    container_name: core2
    build:
      context: ../..
      args:
        CELESTIA_HOME_DIR: /opt
    depends_on:
      - core0
    environment:
      - MONIKER=core2
      - CELESTIA_HOME=/opt
      # private key: 6adac8b5de0ba702ec8feab6d386a0c7334c6720b9174c02333700d431057af8
      - ETH_ADDRESS=0x3d22f0C38251ebdBE92e14BBF1bd2067F1C3b7D7
      - AMOUNT=5000000000uceles
    command: [
      "/bin/bash",
      "/opt/start_node_and_create_validator.sh"
    ]
    volumes:
      - ${PWD}/celestia-app/core2/config/priv_validator_key.json:/opt/config/priv_validator_key.json:ro
      - ${PWD}/celestia-app/core2/config/node_key.json:/opt/config/node_key.json:ro
      - ${PWD}/celestia-app/core2/keyring-test:/opt/keyring-test:ro
      - ${PWD}/celestia-app/start_node_and_create_validator.sh:/opt/start_node_and_create_validator.sh:ro
      - ${PWD}/celestia-app/config.toml:/opt/config/config.toml:ro
      - ${PWD}/celestia-app/genesis.json:/opt/config/genesis.json:ro

  core3:
    container_name: core3
    build:
      context: ../..
      args:
        CELESTIA_HOME_DIR: /opt
    depends_on:
      - core0
    environment:
      - MONIKER=core3
      - CELESTIA_HOME=/opt
      # private key: 2f7f6763500dfb48b710a4c5c6c6a487b8aa6c7bc8b8a9b637a23f651f1c9b51
      - ETH_ADDRESS=0x3EE99606625E740D8b29C8570d855Eb387F3c790
      - AMOUNT=5000000000uceles
    command: [
      "/bin/bash",
      "/opt/start_node_and_create_validator.sh"
    ]
    volumes:
      - ${PWD}/celestia-app/core3/config/priv_validator_key.json:/opt/config/priv_validator_key.json:ro
      - ${PWD}/celestia-app/core3/config/node_key.json:/opt/config/node_key.json:ro
      - ${PWD}/celestia-app/core3/keyring-test:/opt/keyring-test:ro
      - ${PWD}/celestia-app/start_node_and_create_validator.sh:/opt/start_node_and_create_validator.sh:ro
      - ${PWD}/celestia-app/config.toml:/opt/config/config.toml:ro
      - ${PWD}/celestia-app/genesis.json:/opt/config/genesis.json:ro

  ganache:
#    image: ethereum/client-go:alltools-stable
#    command: [
#        "geth",
#        "--datadir=/root/.ethereum/devchain",
##        "--nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322",
#        "--http.api=personal,db,eth,net,web3,txpool,miner",
#        "--http.corsdomain=*",
#        "--maxpeers=0",
#        "--networkid=1234", "--http", "--http.addr=0.0.0.0", "--mine"
#    ]
#    volumes:
##      - ${PWD}/ethereum/password:/root/files/password:ro
#      - ${PWD}/ethereum/genesis.json:/root/files/genesis.json:ro
#      - ${PWD}/ethereum/keystore:/root/.ethereum/devchain/keystore:ro
    image: trufflesuite/ganache-cli
    command: [
      "--port=8545",
      "--host=0.0.0.0",
      "--networkId=1234",
      "--chainId=1234",
      "--account=\"0x1ebff46d79a475ef795be8e8edeb8f7906270af8ad26ba9231b552c3f48c91f9,0x90000000000000000000000\""
    ]
    ports:
      - "8545:8545"
