name: docker-build-publish

# Trigger on all push events, new semantic version tags, and all PRs
on:
  push:
    branches:
      - "main"
      - "v*"
    tags:
      - "v*"
  pull_request:

jobs:
  docker-security-build:
    permissions:
      contents: write
      packages: write
    uses: celestiaorg/.github/.github/workflows/reusable_dockerfile_pipeline.yml@v0.4.3
    with:
      dockerfile: Dockerfile
    secrets: inherit

  docker-txsim-build:
    permissions:
      contents: write
      packages: write
    uses: celestiaorg/.github/.github/workflows/reusable_dockerfile_pipeline.yml@v0.4.3
    with:
      dockerfile: docker/Dockerfile_txsim
      packageName: txsim
    secrets: inherit
