name: Tests / Code Coverage
#  Tests / Code Coverage workflow runs unit tests and uploads a code coverage report
#  This workflow is run on pushes to master & every Pull Requests where a .go, .mod, .sum have been changed
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"

  test-coverage-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.17
      - uses: actions/checkout@v2.4.0
      - uses: technote-space/get-diff-action@v5.0.2
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: build
        run: |
          make build
      - name: test & coverage report creation
        run: |
          go test ./... -mod=readonly -timeout 12m -race -coverprofile=coverage.txt -covermode=atomic -tags='ledger test_ledger_mock'
        if: "env.GIT_DIFF != ''"
      - name: filter out DONTCOVER
        run: |
          excludelist="$(find ./ -type f -name '*.go' | xargs grep -l 'DONTCOVER')"
          excludelist+=" $(find ./ -type f -name '*.pb.go')"
          excludelist+=" $(find ./ -type f -path './tests/mocks/*.go')"
          for filename in ${excludelist}; do
            filename=$(echo $filename | sed 's/^./github.com\/celestiaorg\/celestia-app/g')
            echo "Excluding ${filename} from coverage report..."
            sed -i.bak "/$(echo $filename | sed 's/\//\\\//g')/d" coverage.txt
          done
        if: "env.GIT_DIFF != ''"
      - uses: codecov/codecov-action@v2.1.0
        with:
          file: ./coverage.txt # optional
          fail_ci_if_error: true
        if: "env.GIT_DIFF != ''"
